version: '3.3'

services:
  db:
    image: juxt/xtdb-in-memory:1.22.1
  py:
    build: .
    volumes:
      - .:/code/
    command: pytest --pdb tests.py
    environment:
      - XTDB_URL=http://db:3000
